//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMMCRCNational.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aspnet_ApplicationsDROP20161230
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public aspnet_ApplicationsDROP20161230()
        {
            this.aspnet_MembershipDROP20161230 = new HashSet<aspnet_MembershipDROP20161230>();
            this.aspnet_MembershipDROP201612301 = new HashSet<aspnet_MembershipDROP20161230>();
            this.aspnet_MembershipDROP201612302 = new HashSet<aspnet_MembershipDROP20161230>();
            this.aspnet_PathsDROP20161230 = new HashSet<aspnet_PathsDROP20161230>();
            this.aspnet_PathsDROP201612301 = new HashSet<aspnet_PathsDROP20161230>();
            this.aspnet_PathsDROP201612302 = new HashSet<aspnet_PathsDROP20161230>();
            this.aspnet_UsersDROP20161230 = new HashSet<aspnet_UsersDROP20161230>();
            this.aspnet_UsersDROP201612301 = new HashSet<aspnet_UsersDROP20161230>();
            this.aspnet_UsersDROP201612302 = new HashSet<aspnet_UsersDROP20161230>();
        }
    
        public string ApplicationName { get; set; }
        public string LoweredApplicationName { get; set; }
        public System.Guid ApplicationId { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aspnet_MembershipDROP20161230> aspnet_MembershipDROP20161230 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aspnet_MembershipDROP20161230> aspnet_MembershipDROP201612301 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aspnet_MembershipDROP20161230> aspnet_MembershipDROP201612302 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aspnet_PathsDROP20161230> aspnet_PathsDROP20161230 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aspnet_PathsDROP20161230> aspnet_PathsDROP201612301 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aspnet_PathsDROP20161230> aspnet_PathsDROP201612302 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aspnet_UsersDROP20161230> aspnet_UsersDROP20161230 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aspnet_UsersDROP20161230> aspnet_UsersDROP201612301 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aspnet_UsersDROP20161230> aspnet_UsersDROP201612302 { get; set; }
    }
}
