//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMMCRCNational.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aspnet_PathsDROP20161230
    {
        public System.Guid ApplicationId { get; set; }
        public System.Guid PathId { get; set; }
        public string Path { get; set; }
        public string LoweredPath { get; set; }
    
        public virtual aspnet_ApplicationsDROP20161230 aspnet_ApplicationsDROP20161230 { get; set; }
        public virtual aspnet_ApplicationsDROP20161230 aspnet_ApplicationsDROP201612301 { get; set; }
        public virtual aspnet_ApplicationsDROP20161230 aspnet_ApplicationsDROP201612302 { get; set; }
    }
}
