//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMMCRCNational.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Chapter
    {
        [Key]
        public int ChapterId { get; set; }

        [StringLength(250)]
        public string ChapterName { get; set; }

        [StringLength(150)]
        public string ChapterNickName { get; set; }

        public int? ClubHouseAddressID { get; set; }

        [Column(TypeName = "date")]
        public DateTime? DateModified { get; set; }

        [Column(TypeName = "date")]
        public DateTime? DateCreated { get; set; }

        public string GoogleLink { get; set; }

        [Display(Name = "Is Active")]
        public bool Active { get; set; }
        [NotMapped]
        public string activeValue { get; set; }
    }

}
