//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMMCRCNational.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Event
    {

        public Event()
        {
            // TODO: Complete member initialization
        }
        [Key]
        public int EventId { get; set; }

        [Required]
        public int ChapterId { get; set; }

        [NotMapped]
        public string ChapterName { get; set; }

        [StringLength(250)]
        public string EventTitle { get; set; }

        [Column(TypeName = "date")]
        [DisplayFormat(DataFormatString = "{0:M/dd/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> EventDate { get; set; }

        [Column(TypeName = "date")]
        [DisplayFormat(DataFormatString = "{0:M/dd/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> DateModified { get; set; }

        [Column(TypeName = "date")]
        [DisplayFormat(DataFormatString = "{0:M/dd/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
